name: Ramblings of a Madman
description: General Ramblings About all things JavaScript and Browser Developer Tools

safe: false
lsi: false

language: "en-uk"

author: "Mike Ratcliffe"
nickname: "mikeratcliffe"
bio: "Full Stack JavaScript Developer."
location: "Corby UK"
image: "https://avatars0.githubusercontent.com/u/116941?v=3&s=460"

short_url: "flailingmonkey.com"
google_analytics: UA-5877089-2

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: flailingmonkeycom
twitter: ratcliffe_mike

# Your website URL (e.g. http://barryclark.github.io or
# http://www.barryclark.com). Used for Sitemap.xml and your RSS feed.
url: http://flailingmonkey.com

destination: "./_site"

# edit baseurl to simply '/' if using as your personal page (instead of a
# project page)
baseurl: ""

permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      cover: false
      category: "mikeratcliffe"
      subclass: "post"
      navigation: true

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: rss

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/rss.xml"
  include_posts: "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
